version: '3.8'

services:
  app:
    image: wu529778790/api.shenzjd.com
    container_name: api.shenzjd.com
    ports:
      - '5252:3000' # 将容器的 3000 端口映射到主机的 3000 端口
    volumes:
      - .:/app # 可选：将主机的当前目录挂载到容器的 /app 目录
    environment:
      - NODE_ENV=production # 设置环境变量，可根据需要调整
    restart: on-failure # 只有容器失败时才会重启
    restart_policy:
      delay: 10s # 每次重启的间隔
      max_retries: 3 # 最多重试 3 次
